services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cyber_core_backend
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./backend/.env
    depends_on:
      - qdrant
    networks:
      - cyber_net

  qdrant:
    image: qdrant/qdrant:latest
    container_name: cyber_core_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    networks:
      - cyber_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: "https://zuswmcqwudybxbpxcoaw.supabase.co"
        NEXT_PUBLIC_SUPABASE_ANON_KEY: "sb_publishable_tE5-ptTYbqH2Q9s87JvQiQ_P8HNltYq"
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: cyber_core_frontend
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    depends_on:
      - backend
    networks:
      - cyber_net

networks:
  cyber_net:
    driver: bridge
